// Date: 11/8/2012 9:54:59 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package twilightforest.client.model.entity;

import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.Model;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.util.Mth;
import org.jetbrains.annotations.Nullable;
import twilightforest.block.entity.WebwormBlockEntity;
import twilightforest.client.BugModelAnimationHelper;

public class WebwormModel extends Model {

	private final ModelPart head;
	private final ModelPart shape1;
	private final ModelPart shape2;
	private final ModelPart shape3;
	private final ModelPart shape4;

	public WebwormModel(ModelPart root) {
		super(RenderType::entityTranslucent);

		this.head = root.getChild("head");
		this.shape1 = root.getChild("shape1");
		this.shape2 = root.getChild("shape2");
		this.shape3 = root.getChild("shape3");
		this.shape4 = root.getChild("shape4");
	}

	public static LayerDefinition create() {
		MeshDefinition meshdefinition = new MeshDefinition();
		PartDefinition partdefinition = meshdefinition.getRoot();

		partdefinition.addOrReplaceChild("head", CubeListBuilder.create()
				.texOffs(0, 0)
				.addBox(-1.0F, -1.0F, -1.0F, 2.0F, 2.0F, 2.0F),
			PartPose.offset(0.0F, 6.95F, -4.02F));

		partdefinition.addOrReplaceChild("shape1", CubeListBuilder.create()
				.texOffs(0, 4)
				.addBox(-1.0F, -1.0F, -1.0F, 2.0F, 2.0F, 2.0F),
			PartPose.offset(0.0F, 6.95F, -2.01F));

		partdefinition.addOrReplaceChild("shape2", CubeListBuilder.create()
				.texOffs(0, 8)
				.addBox(-1.0F, -1.0F, -1.0F, 2.0F, 2.0F, 2.0F),
			PartPose.offset(0.0F, 6.95F, 0.0F));

		partdefinition.addOrReplaceChild("shape3", CubeListBuilder.create()
				.texOffs(0, 12)
				.addBox(-1.0F, -1.0F, -1.0F, 2.0F, 2.0F, 2.0F),
			PartPose.offset(0.0F, 6.95F, 2.01F));

		partdefinition.addOrReplaceChild("shape4", CubeListBuilder.create()
				.texOffs(0, 16)
				.addBox(-1.0F, -1.0F, -1.0F, 2.0F, 2.0F, 2.0F),
			PartPose.offset(0.0F, 6.95F, 4.02F));

		return LayerDefinition.create(meshdefinition, 32, 32);
	}

	public void setRotationAngles(@Nullable WebwormBlockEntity webworm, float partialTicks) {
		this.head.y = 6.95F;
		this.shape1.y = 6.95F;
		this.shape2.y = 6.95F;
		this.shape3.y = 6.95F;
		this.shape4.y = 6.95F;

		float shape = webworm != null ? webworm.offset : 200;
		this.head.x = Mth.cos(shape) * 1.5F;
		this.shape1.x = Mth.cos(shape + 1.0F) * 1.5F;
		this.shape2.x = Mth.cos(shape + 2.0F) * 1.5F;
		this.shape3.x = Mth.cos(shape + 3.0F) * 1.5F;
		this.shape4.x = Mth.cos(shape + 4.0F) * 1.5F;

		if (webworm != null && webworm.yawDelay == 0) {
			float time = (webworm.desiredYaw - webworm.currentYaw) - partialTicks;

			// moving
			this.head.y += Math.min(0.0F, Mth.sin(time / 2.0F));
			this.shape1.y += Math.min(0.0F, Mth.sin(time / 2.0F + 1.0F));
			this.shape2.y += Math.min(0.0F, Mth.sin(time / 2.0F + 2.0F));
			this.shape3.y += Math.min(0.0F, Mth.sin(time / 2.0F + 3.0F));
			this.shape4.y += Math.min(0.0F, Mth.sin(time / 2.0F + 4.0F));
		} else if (webworm == null && BugModelAnimationHelper.yawWriggleDelay == 0) {
			float time = (BugModelAnimationHelper.desiredRotation - BugModelAnimationHelper.currentRotation) - partialTicks;

			// moving
			this.head.y += Math.min(0.0F, Mth.sin(time / 2.0F));
			this.shape1.y += Math.min(0.0F, Mth.sin(time / 2.0F + 1.0F));
			this.shape2.y += Math.min(0.0F, Mth.sin(time / 2.0F + 2.0F));
			this.shape3.y += Math.min(0.0F, Mth.sin(time / 2.0F + 3.0F));
			this.shape4.y += Math.min(0.0F, Mth.sin(time / 2.0F + 4.0F));
		}
	}

	@Override
	public void renderToBuffer(PoseStack ms, VertexConsumer buffer, int light, int overlay, int color) {
		this.head.render(ms, buffer, light, overlay, color);
		this.shape1.render(ms, buffer, light, overlay, color);
		this.shape2.render(ms, buffer, light, overlay, color);
		this.shape3.render(ms, buffer, light, overlay, color);
		this.shape4.render(ms, buffer, light, overlay, color);
	}
}
